import { useEffect, useMemo, useState, type ReactNode } from "react";
import { ArrowLeft, ArrowRight, Check, ClipboardCheck, Landmark, PencilLine, ShieldCheck, X } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { DateInput } from "@/components/form/DateInput";
import { formatPrice, getProperty } from "@/data/properties";
import { notify } from "@/lib/notifications";
import { useEntityPlan } from "@/lib/entity-structure";
import { completeTerms, depositAmount, INSPECTION_TYPES, isAttorneyState, propertyCategory, PROPERTY_CATEGORY_LABEL, stateFromLocation, type CommissionPayer, HOME_WARRANTY_LABEL, POSSESSION_LABEL, termsSummary, type AgreementTerms, type HomeWarrantyMode, type PaymentMode, type PossessionMode } from "@/lib/purchase-agreement";
import type { PurchaseRequest } from "@/lib/property-requests";

const STEPS = [
  { id: 1, title: "Offer basics", icon: Landmark },
  { id: 2, title: "Protections", icon: ShieldCheck },
  { id: 3, title: "Deadlines & costs", icon: ClipboardCheck },
  { id: 4, title: "Review & send", icon: Check },
] as const;
const fieldClass = "w-full rounded-md border border-input bg-background px-3 py-2 text-sm text-foreground outline-none placeholder:text-muted-foreground focus:border-brand";
const labelClass = "mb-1.5 block text-xs font-semibold text-foreground";
function Field({ label, children }: { label: string; children: ReactNode }) {
  return <label className="block rounded-md border border-border bg-background p-3"><span className={labelClass}>{label}</span>{children}</label>;
}

export function PurchaseTermsDialog({ open, onOpenChange, leadId, propertyLabel, purchase, buyerName, buyerEmail, agentName }: {
  open: boolean; onOpenChange: (open: boolean) => void; leadId: string; propertyLabel: string; purchase: PurchaseRequest; buyerName: string; buyerEmail?: string | undefined; agentName: string;
}) {
  const { plan, savePlan } = useEntityPlan(leadId);
  const [terms, setTerms] = useState(() => completeTerms((plan?.draftTerms ?? plan?.proposedTerms) as Partial<AgreementTerms> | undefined));
  const [step, setStep] = useState(plan?.termsDraftStep ?? 1);
  const [note, setNote] = useState(plan?.termsNote ?? "");
  const [reviewed, setReviewed] = useState(false);
  const property = getProperty(purchase.propertyId);
  const stateCode = stateFromLocation(property?.location);
  const attorneyState = isAttorneyState(stateCode);
  const category = propertyCategory(property?.type);
  const inspectionOptions = INSPECTION_TYPES[category];
  type Decision = "accepted" | "adjusted" | "declined";
  const requests = plan?.termsChangeRequestedAt ? plan?.termsChangeItems ?? [] : [];
  const [responses, setResponses] = useState<Record<string, { decision: Decision; reason?: string }>>({});
  const STEP_OF: Record<string, number> = { closing: 1, deposit: 1, possession: 1, inspection: 2, appraisal: 2, financing: 2, attorney: 3, commission: 3, concessions: 3, warranty: 3, items: 3, expiry: 3, other: 4 };
  function respond(label: string, decision: Decision, reason?: string) {
    setResponses((r) => { const next = { ...r, [label]: { decision, reason } }; savePlan({ termsChangeResponses: requests.map((q) => next[q.label] ? { label: q.label, to: q.to, ...next[q.label]! } : null).filter(Boolean) as NonNullable<typeof plan>["termsChangeResponses"] }); return next; });
  }
  const unanswered = requests.filter((q) => { const r = responses[q.label]; return !r || (r.decision === "declined" && !r.reason?.trim()); }).length;
  const previousRows = useMemo(() => plan?.proposedTerms ? Object.fromEntries(termsSummary(purchase.offerPrice, completeTerms(plan.proposedTerms as Partial<AgreementTerms>)).map((r) => [r.label, r.value])) : {}, [plan?.proposedTerms, purchase.offerPrice]);
  const alreadyConfirmed = Boolean(plan?.termsConfirmedAt && !plan?.termsChangeRequestedAt);

  useEffect(() => {
    if (!open) return;
    setTerms({ ...completeTerms((plan?.draftTerms ?? plan?.proposedTerms) as Partial<AgreementTerms> | undefined), attorneyApplicable: attorneyState });
    setStep(Math.min(4, Math.max(1, plan?.termsDraftStep ?? 1)));
    setNote(plan?.termsNote ?? "");
    setReviewed(false);
    setResponses(plan?.termsChangeRequestedAt ? Object.fromEntries((plan?.termsChangeResponses ?? []).map((r) => [r.label, { decision: r.decision, reason: r.reason }])) : {});
  }, [open]);

  const selectedProtections = useMemo(() => [terms.inspection, terms.appraisal, terms.financing].filter(Boolean).length, [terms]);
  function patch(next: Partial<AgreementTerms>) {
    setTerms((current) => { const merged = { ...current, ...next }; const updated = { ...merged, attorneyApplicable: attorneyState, inspectionDays: merged.inspectionDeadlineDays, financingDays: merged.finalLoanApprovalDays }; savePlan({ draftTerms: updated }); return updated; });
  }
  function goTo(next: number) {
    const bounded = Math.min(4, Math.max(1, next)); setStep(bounded); savePlan({ draftTerms: terms, termsDraftStep: bounded, termsNote: note.trim() || undefined });
  }
  function sendToBuyer() {
    if (!reviewed) return;
    if (unanswered) { toast(`Answer all ${requests.length} buyer requests first`, { description: "Confirm, adjust or decline (with a reason) each requested change." }); return; }
    if (!terms.closingDate) { toast("Add the target closing date before sending."); return; }
    if (terms.depositMode === "custom" && !(terms.depositAmount > 0)) { toast("Enter the custom escrow amount."); return; }
    if (terms.inspection && terms.inspectionTypes.length === 0) { toast("Choose at least one inspection type."); return; }
    const now = new Date().toISOString();
    savePlan({ draftTerms: terms, proposedTerms: terms, termsProposedAt: now, termsProposedBy: agentName, termsRound: (plan?.termsRound ?? 0) + 1, termsNote: note.trim() || undefined, termsChangeRequestedAt: undefined, termsChangeNote: undefined, termsChangeItems: undefined, termsChangeResponses: requests.length ? requests.map((q) => ({ label: q.label, to: q.to, ...responses[q.label]! })) : undefined, termsConfirmedAt: undefined, termsConfirmedBy: undefined, termsDraftStep: 4 });
    if (buyerEmail) notify({ id: `terms-proposed-${leadId}-${(plan?.termsRound ?? 0) + 1}`, to: buyerEmail.toLowerCase(), title: "Your agent proposed the purchase terms — your confirmation is needed", body: requests.length ? `${propertyLabel}: your agent answered your change requests — ${requests.map((q) => `${q.label}: ${responses[q.label]?.decision === "declined" ? `not possible (${responses[q.label]?.reason})` : responses[q.label]?.decision}`).join("; ")}. Review the revised terms.` : `${propertyLabel} at ${formatPrice(purchase.offerPrice)}. Review the complete terms before they are presented to the seller.`, href: `/property/${purchase.propertyId}/workspace?open=agreement`, severity: "warning" });
    toast("Terms sent to the buyer", { description: `${buyerName} must confirm them before they go to the seller.` }); onOpenChange(false);
  }

  const checks: [keyof AgreementTerms, string, string][] = [
    ["inspection", "Inspection contingency", "Inspect, request repairs or credits, or withdraw by the deadline."],
    ["appraisal", "Appraisal contingency", "Protection if the appraised value is below the purchase price."],
    ["financing", "Financing / mortgage contingency", "The purchase depends on obtaining the agreed financing."],
  ];
  const deadlines: [keyof AgreementTerms, string, boolean][] = [["inspectionDeadlineDays", "Inspection period ends", terms.inspection], ["appraisalDeadlineDays", "Appraisal deadline", terms.appraisal], ["mortgageSubmissionDays", "Mortgage submission deadline", terms.financing], ["finalLoanApprovalDays", "Final loan approval deadline", terms.financing], ["offerExpiresDays", "Offer expiration", true]];

  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="flex max-h-[92vh] max-w-5xl flex-col gap-0 overflow-hidden p-0">
    <DialogHeader className="border-b border-border px-5 py-4 pr-12"><DialogTitle>Purchase terms for {buyerName}</DialogTitle><DialogDescription>{propertyLabel} · Buyer offer {formatPrice(purchase.offerPrice)} · Draft saves automatically</DialogDescription></DialogHeader>
    <ol className="grid grid-cols-2 border-b border-border bg-muted/30 sm:grid-cols-4">{STEPS.map(({ id, title, icon: Icon }) => <li key={id}><Button type="button" variant="ghost" onClick={() => goTo(id)} className={`flex h-14 w-full items-center justify-start gap-2 rounded-none border-r border-border px-3 text-left text-xs font-semibold last:border-r-0 ${step === id ? "bg-brand-tint text-brand hover:bg-brand-tint" : id < step ? "text-success" : "text-muted-foreground"}`}><span className={`grid h-6 w-6 shrink-0 place-items-center rounded-full border ${step === id ? "border-brand bg-brand text-background" : id < step ? "border-success bg-success/10" : "border-border bg-background"}`}>{id < step ? <Check /> : <Icon />}</span><span>{id}. {title}</span></Button></li>)}</ol>
    {requests.length ? <div className="max-h-[38vh] shrink-0 overflow-y-auto border-b border-gold/40 bg-gold-tint/30 px-5 py-3"><div className="flex flex-wrap items-center justify-between gap-2"><span className="inline-flex items-center gap-1.5 text-sm font-semibold text-foreground"><PencilLine className="h-4 w-4 text-gold" />{buyerName} requested {requests.length} change{requests.length === 1 ? "" : "s"}</span><span className={`rounded-full px-2.5 py-0.5 text-[11px] font-semibold ${unanswered ? "bg-gold text-background" : "bg-success/15 text-success"}`}>{unanswered ? `${unanswered} to answer` : "All answered"}</span></div>
      <ul className="mt-2 space-y-2">{requests.map((q) => { const r = responses[q.label]; return <li key={q.label} className={`rounded-md border bg-background p-3 ${r ? r.decision === "declined" ? "border-destructive/40" : "border-success/40" : "border-gold/60 ring-1 ring-gold/30"}`}>
        <div className="flex flex-wrap items-start justify-between gap-2"><div className="min-w-0"><div className="flex items-center gap-2"><span className="rounded bg-gold px-1.5 py-0.5 text-[10px] font-bold uppercase text-background">New request</span><span className="text-xs font-bold uppercase tracking-wide text-muted-foreground">{q.label}</span></div><div className="mt-1.5 flex flex-wrap items-center gap-2 text-xs">{q.from ? <><span className="rounded bg-muted px-2 py-1 text-muted-foreground line-through">{q.from}</span><ArrowRight className="h-3 w-3 text-brand" /></> : null}<span className="rounded border border-gold/50 px-2 py-1 font-semibold text-foreground">{q.to}</span></div></div>
        <div className="flex flex-wrap gap-1.5"><Button type="button" size="sm" variant={r?.decision === "accepted" ? "default" : "outline"} onClick={() => { if (q.patch) patch(q.patch as Partial<AgreementTerms>); respond(q.label, "accepted"); }}><Check />Confirm</Button><Button type="button" size="sm" variant={r?.decision === "adjusted" ? "default" : "outline"} onClick={() => { respond(q.label, "adjusted"); goTo(STEP_OF[q.key ?? ""] ?? 1); }}><PencilLine />Adjust</Button><Button type="button" size="sm" variant={r?.decision === "declined" ? "destructive" : "outline"} onClick={() => respond(q.label, "declined", r?.reason)}><X />Decline</Button></div></div>
        {r?.decision === "declined" ? <textarea rows={2} value={r.reason ?? ""} onChange={(e) => respond(q.label, "declined", e.target.value)} placeholder={`Why this isn't possible — ${buyerName} will see this`} className={`${fieldClass} mt-2`} /> : r?.decision === "accepted" ? <p className="mt-2 text-xs text-success">Applied to the terms below.</p> : r?.decision === "adjusted" ? <p className="mt-2 text-xs text-muted-foreground">Edit this term in the section below — your counter-value will be highlighted in the summary.</p> : null}
      </li>; })}</ul>{plan?.termsChangeNote ? <p className="mt-2 text-xs italic text-muted-foreground">Buyer's note: “{plan.termsChangeNote}”</p> : null}</div> : null}
    <div className="min-h-0 flex-1 overflow-y-auto px-5 py-5">
      {step === 1 ? <div className="space-y-4"><div><h3 className="text-base font-semibold text-foreground">Offer basics</h3><p className="mt-1 text-sm text-muted-foreground">Set the deposit, payment, closing and handover terms.</p></div><div className="grid gap-3 md:grid-cols-2">
        <Field label="Earnest money deposit"><div className="flex flex-wrap gap-2">{[5, 10, 15].map((amount) => <Button key={amount} type="button" size="sm" variant={terms.depositMode !== "custom" && terms.depositPct === amount ? "default" : "outline"} onClick={() => patch({ depositMode: "pct", depositPct: amount })}>{amount}%</Button>)}<Button type="button" size="sm" variant={terms.depositMode === "custom" ? "default" : "outline"} onClick={() => patch({ depositMode: "custom" })}>Custom amount</Button></div>{terms.depositMode === "custom" ? <input type="number" min="0" step="1000" value={terms.depositAmount || ""} placeholder="Escrow amount in USD" onChange={(e) => patch({ depositAmount: Number(e.target.value) })} className={`${fieldClass} mt-2`} /> : null}<p className="mt-2 text-xs text-muted-foreground">{formatPrice(depositAmount(purchase.offerPrice, terms))} held in escrow</p></Field>
        <Field label="Deposit due (business days)"><input type="number" min="1" value={terms.depositDays} onChange={(e) => patch({ depositDays: Number(e.target.value) })} className={fieldClass} /></Field>
        <Field label="How the purchase is paid"><select value={terms.paymentMode} onChange={(e) => patch({ paymentMode: e.target.value as PaymentMode })} className={fieldClass}><option value="financed">Mortgage</option><option value="cash">All cash</option><option value="seller_finance">Seller financing</option></select></Field>
        <Field label="Target closing date"><DateInput value={terms.closingDate} onChange={(value) => patch({ closingDate: value })} className={fieldClass} /></Field>
        <Field label="Possession / key handover"><select value={terms.possession} onChange={(e) => patch({ possession: e.target.value as PossessionMode })} className={fieldClass}>{Object.entries(POSSESSION_LABEL).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field>
        {attorneyState ? <Field label="Attorney review (business days)"><input type="number" min="0" value={terms.attorneyReviewDays} onChange={(e) => patch({ attorneyReviewDays: Number(e.target.value) })} className={fieldClass} /><p className="mt-2 text-xs text-muted-foreground">{stateCode} is an attorney state.</p></Field> : <div className="rounded-md border border-dashed border-border bg-muted/30 p-3 text-xs text-muted-foreground"><span className="block font-semibold text-foreground">Attorney review</span>Not applicable — {stateCode ?? "this state"} is not an attorney state.</div>}
      </div></div> : null}
      {step === 2 ? <div className="space-y-4"><div><h3 className="text-base font-semibold text-foreground">Contingencies and protections</h3><p className="mt-1 text-sm text-muted-foreground">Choose the safeguards that should be carried into the offer.</p></div><div className="grid gap-2 md:grid-cols-2">{checks.map(([key, title, detail]) => <label key={key} className="flex cursor-pointer gap-3 rounded-md border border-border bg-background p-3"><input type="checkbox" checked={Boolean(terms[key])} onChange={(e) => patch({ [key]: e.target.checked })} className="mt-1 accent-brand" /><span><span className="block text-sm font-semibold text-foreground">{title}</span><span className="mt-1 block text-xs leading-5 text-muted-foreground">{detail}</span></span></label>)}</div>{terms.inspection ? <div className="rounded-md border border-border bg-background p-3"><div className="flex flex-wrap items-center justify-between gap-2"><span className="text-sm font-semibold text-foreground">Inspections to carry out</span><span className="rounded-full bg-muted px-2.5 py-0.5 text-[11px] font-semibold text-muted-foreground">{PROPERTY_CATEGORY_LABEL[category]}</span></div><p className="mt-1 text-xs text-muted-foreground">Showing the inspections that apply to this type of property.</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{inspectionOptions.map((name) => { const on = terms.inspectionTypes.includes(name); return <label key={name} className={`flex cursor-pointer items-center gap-2 rounded-md border px-3 py-2 text-sm ${on ? "border-brand bg-brand-tint/40 text-foreground" : "border-border text-muted-foreground"}`}><input type="checkbox" checked={on} onChange={(e) => patch({ inspectionTypes: e.target.checked ? [...terms.inspectionTypes, name] : terms.inspectionTypes.filter((x) => x !== name) })} className="accent-brand" />{name}</label>; })}</div></div> : null}</div> : null}
      {step === 3 ? <div className="space-y-5"><div><h3 className="text-base font-semibold text-foreground">Deadlines and costs</h3><p className="mt-1 text-sm text-muted-foreground">Deadlines are counted in days from signing the agreement.</p></div><section><h4 className="mb-2 text-sm font-semibold text-foreground">Important deadlines</h4><div className="grid gap-3 md:grid-cols-2">{deadlines.filter(([, , show]) => show).map(([key, label]) => <Field key={key} label={`${label} (days from signing)`}><input type="number" min="1" value={Number(terms[key])} onChange={(e) => patch({ [key]: Number(e.target.value) })} className={fieldClass} /></Field>)}</div></section><section><h4 className="mb-2 text-sm font-semibold text-foreground">Property and costs</h4><div className="grid gap-3 md:grid-cols-2">
        <Field label="Included with the property"><input value={terms.includedItems} onChange={(e) => patch({ includedItems: e.target.value })} className={fieldClass} /></Field><Field label="Excluded from the sale"><input value={terms.excludedItems} onChange={(e) => patch({ excludedItems: e.target.value })} className={fieldClass} /></Field>
        <Field label="Seller concessions / credits"><input value={terms.sellerConcessions} onChange={(e) => patch({ sellerConcessions: e.target.value })} placeholder="Amount, terms, or none" className={fieldClass} /></Field><Field label="Home warranty"><select value={terms.homeWarranty} onChange={(e) => patch({ homeWarranty: e.target.value as HomeWarrantyMode })} className={fieldClass}>{Object.entries(HOME_WARRANTY_LABEL).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field>
        <Field label="Buyer's agent commission (%)"><input type="number" min="0" max="6" step="0.5" value={terms.commissionPct} onChange={(e) => patch({ commissionPct: Number(e.target.value) })} className={fieldClass} /></Field><Field label="Who pays the buyer's agent commission"><select value={terms.commissionPayer} onChange={(e) => patch({ commissionPayer: e.target.value as CommissionPayer })} className={fieldClass}><option value="seller">Seller</option><option value="buyer">Buyer</option><option value="split">Split between both</option></select>{terms.commissionPayer === "split" ? <div className="mt-2 flex items-center gap-2 text-xs text-muted-foreground"><span>Seller pays</span><input type="number" min="0" max="100" step="5" value={terms.commissionSellerSharePct} onChange={(e) => patch({ commissionSellerSharePct: Math.min(100, Math.max(0, Number(e.target.value))) })} className={`${fieldClass} w-20`} /><span>% · buyer pays {100 - terms.commissionSellerSharePct}%</span></div> : null}</Field>
        <div className="md:col-span-2"><Field label="Additional terms"><textarea rows={3} value={terms.specialTerms} onChange={(e) => patch({ specialTerms: e.target.value })} placeholder="Repairs, credits, lease details, personal property, or other negotiated terms" className={fieldClass} /></Field></div>
      </div></section></div> : null}
      {step === 4 ? <div className="space-y-4"><div><h3 className="text-base font-semibold text-foreground">Review before sending</h3><p className="mt-1 text-sm text-muted-foreground">This is exactly what {buyerName} will review and confirm before anything goes to the seller.</p></div><div className="grid gap-x-6 rounded-md border border-border bg-background p-4 md:grid-cols-2">{termsSummary(purchase.offerPrice, terms).map((row) => { const changed = plan?.proposedTerms && previousRows[row.label] !== undefined && previousRows[row.label] !== row.value; return <div key={row.label} className={`border-b border-border/60 py-2.5 ${changed ? "-mx-2 rounded-md border-gold/50 bg-gold-tint/40 px-2" : ""}`}><div className="flex items-center gap-2 text-[11px] font-semibold uppercase text-muted-foreground">{row.label}{changed ? <span className="rounded bg-gold px-1.5 py-0.5 text-[9px] font-bold text-background">Updated</span> : null}</div>{changed ? <div className="mt-1 text-xs text-muted-foreground line-through">{previousRows[row.label]}</div> : null}<div className={`mt-1 text-sm text-foreground ${changed ? "font-semibold" : ""}`}>{row.value}</div></div>; })}</div><label className="block"><span className={labelClass}>Note to {buyerName} (optional)</span><textarea rows={3} value={note} disabled={alreadyConfirmed} onChange={(e) => { setNote(e.target.value); savePlan({ termsNote: e.target.value || undefined }); }} className={fieldClass} placeholder="Explain why you recommend these terms." /></label><div className={`rounded-md border p-3 text-sm text-foreground ${alreadyConfirmed ? "border-success/30 bg-success/10" : "border-brand/30 bg-brand-tint/30"}`}><strong>{alreadyConfirmed ? `Confirmed by ${buyerName} — ready for the seller.` : `${selectedProtections} protections selected.`}</strong> {alreadyConfirmed ? "If the seller proposes different terms, prepare a revised version for the buyer to confirm." : "The buyer may confirm these terms or request changes. Only confirmed terms can be presented to the seller."}</div>{!alreadyConfirmed ? <label className="flex cursor-pointer items-start gap-3 rounded-md border border-border p-3"><input type="checkbox" checked={reviewed} onChange={(e) => setReviewed(e.target.checked)} className="mt-1 accent-brand" /><span className="text-sm font-medium text-foreground">I reviewed these terms and they are ready to send to {buyerName}.</span></label> : null}</div> : null}
    </div>
    <div className="flex flex-col-reverse gap-2 border-t border-border bg-background px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><Button type="button" variant="outline" disabled={step === 1} onClick={() => goTo(step - 1)}><ArrowLeft />Back</Button><div className="flex items-center justify-end gap-2"><span className="mr-2 hidden text-xs text-success sm:inline">Draft saved</span>{step < 4 ? <Button type="button" onClick={() => goTo(step + 1)}>Continue<ArrowRight /></Button> : alreadyConfirmed ? <Button type="button" onClick={() => onOpenChange(false)}><Check />Ready for seller</Button> : <Button type="button" disabled={!reviewed || unanswered > 0} onClick={sendToBuyer}><Check />{requests.length ? "Send revised terms to buyer" : "Send to buyer for confirmation"}</Button>}</div></div>
  </DialogContent></Dialog>;
}
