/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as FinancialsRouteImport } from './routes/financials'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as MyPropertiesRouteImport } from './routes/my-properties'
import { Route as MyServicesRouteImport } from './routes/my-services'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as SsnTermsRouteImport } from './routes/ssn-terms'
import { Route as PropertyPropertyIdRouteImport } from './routes/property.$propertyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialsRoute = FinancialsRouteImport.update({
  id: '/financials',
  path: '/financials',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPropertiesRoute = MyPropertiesRouteImport.update({
  id: '/my-properties',
  path: '/my-properties',
  getParentRoute: () => rootRouteImport,
} as any)
const MyServicesRoute = MyServicesRouteImport.update({
  id: '/my-services',
  path: '/my-services',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const SsnTermsRoute = SsnTermsRouteImport.update({
  id: '/ssn-terms',
  path: '/ssn-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyPropertyIdRoute = PropertyPropertyIdRouteImport.update({
  id: '/property/$propertyId',
  path: '/property/$propertyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/documents': typeof DocumentsRoute
  '/financials': typeof FinancialsRoute
  '/marketplace': typeof MarketplaceRoute
  '/my-properties': typeof MyPropertiesRoute
  '/my-services': typeof MyServicesRoute
  '/partner': typeof PartnerRoute
  '/ssn-terms': typeof SsnTermsRoute
  '/property/$propertyId': typeof PropertyPropertyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/documents': typeof DocumentsRoute
  '/financials': typeof FinancialsRoute
  '/marketplace': typeof MarketplaceRoute
  '/my-properties': typeof MyPropertiesRoute
  '/my-services': typeof MyServicesRoute
  '/partner': typeof PartnerRoute
  '/ssn-terms': typeof SsnTermsRoute
  '/property/$propertyId': typeof PropertyPropertyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/documents': typeof DocumentsRoute
  '/financials': typeof FinancialsRoute
  '/marketplace': typeof MarketplaceRoute
  '/my-properties': typeof MyPropertiesRoute
  '/my-services': typeof MyServicesRoute
  '/partner': typeof PartnerRoute
  '/ssn-terms': typeof SsnTermsRoute
  '/property/$propertyId': typeof PropertyPropertyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/auth'
    | '/documents'
    | '/financials'
    | '/marketplace'
    | '/my-properties'
    | '/my-services'
    | '/partner'
    | '/ssn-terms'
    | '/property/$propertyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/auth'
    | '/documents'
    | '/financials'
    | '/marketplace'
    | '/my-properties'
    | '/my-services'
    | '/partner'
    | '/ssn-terms'
    | '/property/$propertyId'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/auth'
    | '/documents'
    | '/financials'
    | '/marketplace'
    | '/my-properties'
    | '/my-services'
    | '/partner'
    | '/ssn-terms'
    | '/property/$propertyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRoute
  DocumentsRoute: typeof DocumentsRoute
  FinancialsRoute: typeof FinancialsRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MyPropertiesRoute: typeof MyPropertiesRoute
  MyServicesRoute: typeof MyServicesRoute
  PartnerRoute: typeof PartnerRoute
  SsnTermsRoute: typeof SsnTermsRoute
  PropertyPropertyIdRoute: typeof PropertyPropertyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financials': {
      id: '/financials'
      path: '/financials'
      fullPath: '/financials'
      preLoaderRoute: typeof FinancialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-properties': {
      id: '/my-properties'
      path: '/my-properties'
      fullPath: '/my-properties'
      preLoaderRoute: typeof MyPropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-services': {
      id: '/my-services'
      path: '/my-services'
      fullPath: '/my-services'
      preLoaderRoute: typeof MyServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ssn-terms': {
      id: '/ssn-terms'
      path: '/ssn-terms'
      fullPath: '/ssn-terms'
      preLoaderRoute: typeof SsnTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/$propertyId': {
      id: '/property/$propertyId'
      path: '/property/$propertyId'
      fullPath: '/property/$propertyId'
      preLoaderRoute: typeof PropertyPropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRoute,
  DocumentsRoute: DocumentsRoute,
  FinancialsRoute: FinancialsRoute,
  MarketplaceRoute: MarketplaceRoute,
  MyPropertiesRoute: MyPropertiesRoute,
  MyServicesRoute: MyServicesRoute,
  PartnerRoute: PartnerRoute,
  SsnTermsRoute: SsnTermsRoute,
  PropertyPropertyIdRoute: PropertyPropertyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
