/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminPartnerRequestsRouteImport } from './routes/admin-partner-requests'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FinancialsRouteImport } from './routes/financials'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as MyPropertiesRouteImport } from './routes/my-properties'
import { Route as MyServicesRouteImport } from './routes/my-services'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as PartnerAccessRouteImport } from './routes/partner-access'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SsnTermsRouteImport } from './routes/ssn-terms'
import { Route as AdminPeoplePersonIdRouteImport } from './routes/admin-people.$personId'
import { Route as ApplicationLeadIdRouteImport } from './routes/application.$leadId'
import { Route as PropertyPropertyIdRouteImport } from './routes/property.$propertyId'
import { Route as LenderFileLeadIdRouteImport } from './routes/lender.file.$leadId'
import { Route as OauthGoogleReturnRouteImport } from './routes/oauth.google.return'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPartnerRequestsRoute = AdminPartnerRequestsRouteImport.update({
  id: '/admin-partner-requests',
  path: '/admin-partner-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialsRoute = FinancialsRouteImport.update({
  id: '/financials',
  path: '/financials',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPropertiesRoute = MyPropertiesRouteImport.update({
  id: '/my-properties',
  path: '/my-properties',
  getParentRoute: () => rootRouteImport,
} as any)
const MyServicesRoute = MyServicesRouteImport.update({
  id: '/my-services',
  path: '/my-services',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerAccessRoute = PartnerAccessRouteImport.update({
  id: '/partner-access',
  path: '/partner-access',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SsnTermsRoute = SsnTermsRouteImport.update({
  id: '/ssn-terms',
  path: '/ssn-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPeoplePersonIdRoute = AdminPeoplePersonIdRouteImport.update({
  id: '/admin-people/$personId',
  path: '/admin-people/$personId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationLeadIdRoute = ApplicationLeadIdRouteImport.update({
  id: '/application/$leadId',
  path: '/application/$leadId',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyPropertyIdRoute = PropertyPropertyIdRouteImport.update({
  id: '/property/$propertyId',
  path: '/property/$propertyId',
  getParentRoute: () => rootRouteImport,
} as any)
const LenderFileLeadIdRoute = LenderFileLeadIdRouteImport.update({
  id: '/lender/file/$leadId',
  path: '/lender/file/$leadId',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthGoogleReturnRoute = OauthGoogleReturnRouteImport.update({
  id: '/oauth/google/return',
  path: '/oauth/google/return',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-partner-requests': typeof AdminPartnerRequestsRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/documents': typeof DocumentsRoute
  '/faq': typeof FaqRoute
  '/financials': typeof FinancialsRoute
  '/marketplace': typeof MarketplaceRoute
  '/my-properties': typeof MyPropertiesRoute
  '/my-services': typeof MyServicesRoute
  '/partner': typeof PartnerRoute
  '/partner-access': typeof PartnerAccessRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/ssn-terms': typeof SsnTermsRoute
  '/admin-people/$personId': typeof AdminPeoplePersonIdRoute
  '/application/$leadId': typeof ApplicationLeadIdRoute
  '/property/$propertyId': typeof PropertyPropertyIdRoute
  '/lender/file/$leadId': typeof LenderFileLeadIdRoute
  '/oauth/google/return': typeof OauthGoogleReturnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-partner-requests': typeof AdminPartnerRequestsRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/documents': typeof DocumentsRoute
  '/faq': typeof FaqRoute
  '/financials': typeof FinancialsRoute
  '/marketplace': typeof MarketplaceRoute
  '/my-properties': typeof MyPropertiesRoute
  '/my-services': typeof MyServicesRoute
  '/partner': typeof PartnerRoute
  '/partner-access': typeof PartnerAccessRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/ssn-terms': typeof SsnTermsRoute
  '/admin-people/$personId': typeof AdminPeoplePersonIdRoute
  '/application/$leadId': typeof ApplicationLeadIdRoute
  '/property/$propertyId': typeof PropertyPropertyIdRoute
  '/lender/file/$leadId': typeof LenderFileLeadIdRoute
  '/oauth/google/return': typeof OauthGoogleReturnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-partner-requests': typeof AdminPartnerRequestsRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/documents': typeof DocumentsRoute
  '/faq': typeof FaqRoute
  '/financials': typeof FinancialsRoute
  '/marketplace': typeof MarketplaceRoute
  '/my-properties': typeof MyPropertiesRoute
  '/my-services': typeof MyServicesRoute
  '/partner': typeof PartnerRoute
  '/partner-access': typeof PartnerAccessRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/ssn-terms': typeof SsnTermsRoute
  '/admin-people/$personId': typeof AdminPeoplePersonIdRoute
  '/application/$leadId': typeof ApplicationLeadIdRoute
  '/property/$propertyId': typeof PropertyPropertyIdRoute
  '/lender/file/$leadId': typeof LenderFileLeadIdRoute
  '/oauth/google/return': typeof OauthGoogleReturnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-partner-requests'
    | '/analytics'
    | '/auth'
    | '/documents'
    | '/faq'
    | '/financials'
    | '/marketplace'
    | '/my-properties'
    | '/my-services'
    | '/partner'
    | '/partner-access'
    | '/profile'
    | '/reset-password'
    | '/settings'
    | '/ssn-terms'
    | '/admin-people/$personId'
    | '/application/$leadId'
    | '/property/$propertyId'
    | '/lender/file/$leadId'
    | '/oauth/google/return'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-partner-requests'
    | '/analytics'
    | '/auth'
    | '/documents'
    | '/faq'
    | '/financials'
    | '/marketplace'
    | '/my-properties'
    | '/my-services'
    | '/partner'
    | '/partner-access'
    | '/profile'
    | '/reset-password'
    | '/settings'
    | '/ssn-terms'
    | '/admin-people/$personId'
    | '/application/$leadId'
    | '/property/$propertyId'
    | '/lender/file/$leadId'
    | '/oauth/google/return'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-partner-requests'
    | '/analytics'
    | '/auth'
    | '/documents'
    | '/faq'
    | '/financials'
    | '/marketplace'
    | '/my-properties'
    | '/my-services'
    | '/partner'
    | '/partner-access'
    | '/profile'
    | '/reset-password'
    | '/settings'
    | '/ssn-terms'
    | '/admin-people/$personId'
    | '/application/$leadId'
    | '/property/$propertyId'
    | '/lender/file/$leadId'
    | '/oauth/google/return'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminPartnerRequestsRoute: typeof AdminPartnerRequestsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRoute
  DocumentsRoute: typeof DocumentsRoute
  FaqRoute: typeof FaqRoute
  FinancialsRoute: typeof FinancialsRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MyPropertiesRoute: typeof MyPropertiesRoute
  MyServicesRoute: typeof MyServicesRoute
  PartnerRoute: typeof PartnerRoute
  PartnerAccessRoute: typeof PartnerAccessRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SsnTermsRoute: typeof SsnTermsRoute
  AdminPeoplePersonIdRoute: typeof AdminPeoplePersonIdRoute
  ApplicationLeadIdRoute: typeof ApplicationLeadIdRoute
  PropertyPropertyIdRoute: typeof PropertyPropertyIdRoute
  LenderFileLeadIdRoute: typeof LenderFileLeadIdRoute
  OauthGoogleReturnRoute: typeof OauthGoogleReturnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-partner-requests': {
      id: '/admin-partner-requests'
      path: '/admin-partner-requests'
      fullPath: '/admin-partner-requests'
      preLoaderRoute: typeof AdminPartnerRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financials': {
      id: '/financials'
      path: '/financials'
      fullPath: '/financials'
      preLoaderRoute: typeof FinancialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-properties': {
      id: '/my-properties'
      path: '/my-properties'
      fullPath: '/my-properties'
      preLoaderRoute: typeof MyPropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-services': {
      id: '/my-services'
      path: '/my-services'
      fullPath: '/my-services'
      preLoaderRoute: typeof MyServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-access': {
      id: '/partner-access'
      path: '/partner-access'
      fullPath: '/partner-access'
      preLoaderRoute: typeof PartnerAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ssn-terms': {
      id: '/ssn-terms'
      path: '/ssn-terms'
      fullPath: '/ssn-terms'
      preLoaderRoute: typeof SsnTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-people/$personId': {
      id: '/admin-people/$personId'
      path: '/admin-people/$personId'
      fullPath: '/admin-people/$personId'
      preLoaderRoute: typeof AdminPeoplePersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/application/$leadId': {
      id: '/application/$leadId'
      path: '/application/$leadId'
      fullPath: '/application/$leadId'
      preLoaderRoute: typeof ApplicationLeadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/$propertyId': {
      id: '/property/$propertyId'
      path: '/property/$propertyId'
      fullPath: '/property/$propertyId'
      preLoaderRoute: typeof PropertyPropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lender/file/$leadId': {
      id: '/lender/file/$leadId'
      path: '/lender/file/$leadId'
      fullPath: '/lender/file/$leadId'
      preLoaderRoute: typeof LenderFileLeadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/google/return': {
      id: '/oauth/google/return'
      path: '/oauth/google/return'
      fullPath: '/oauth/google/return'
      preLoaderRoute: typeof OauthGoogleReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminPartnerRequestsRoute: AdminPartnerRequestsRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRoute,
  DocumentsRoute: DocumentsRoute,
  FaqRoute: FaqRoute,
  FinancialsRoute: FinancialsRoute,
  MarketplaceRoute: MarketplaceRoute,
  MyPropertiesRoute: MyPropertiesRoute,
  MyServicesRoute: MyServicesRoute,
  PartnerRoute: PartnerRoute,
  PartnerAccessRoute: PartnerAccessRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SsnTermsRoute: SsnTermsRoute,
  AdminPeoplePersonIdRoute: AdminPeoplePersonIdRoute,
  ApplicationLeadIdRoute: ApplicationLeadIdRoute,
  PropertyPropertyIdRoute: PropertyPropertyIdRoute,
  LenderFileLeadIdRoute: LenderFileLeadIdRoute,
  OauthGoogleReturnRoute: OauthGoogleReturnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
